### ISSUE TITLE
App crashes in Homey V2.0

### ISSUE THREAD

**Issue by ghost** [hilvarenbeek/nl.marcovandenhout.marantz#20]
When tapping a flow card the Homey app crashes. Will there be an update for Homey V2.0?

**Comment by hilvarenbeek** [comment]
I could reproduce this by tapping an action card on the Android app. Trying to find the problem. The app should already be V2 ready.

**Comment by hilvarenbeek** [comment]
Should be fixed in 1.0.3

**Comment by hilvarenbeek** [comment]
Can you check with 1.0.3 (currently in beta on the app store)? Not sure if an already 'bad' flow will now work, but new flows should.

**Comment by ghost** [comment]
I installed v1.03 of the app. When trying to edit the "then" flow card, the Homey app crashes. But when a new flow is made with the exact same parameters and saved, I can open it afterwards to edit the flow cards.
So to me it seems to be solved.
Thanks!

**Comment by hilvarenbeek** [comment]
1.0.4 is now in the main app store.
