### ISSUE TITLE
Get white screen when zone changed

### ISSUE THREAD

**Issue by madmax75** [hilvarenbeek/nl.marcovandenhout.marantz#21]
Get an white screen when I change the zone in then flow card.

**Comment by hilvarenbeek** [comment]
Can you give more information about the issue? Like the app & OS you're using? I have the Athom 2.0 beta app on Android and it sometimes crashes on me, but unfortunately I can't see anything in the debug logs of the Marantz app when that happens.

**Comment by madmax75** [comment]
It's the iOS Final App.

**Comment by madmax75** [comment]
I’m using the final iOS app 2.0 and the last stable 2.0. When I chose in the when card change volume an chose the zone then I get a blank white screen.

![2019-01-20 20 28 34](https://user-images.githubusercontent.com/29087006/51444095-3eef1f80-1cf3-11e9-83d9-82c347f0d5c4.png)

**Comment by hilvarenbeek** [comment]
There's definitely an issue with flow, I got it when chosing input on a 'when.. input changed to...' card.

**Comment by madmax75** [comment]
Yes same here. I get an blank white screen in the and card by choosing “input source is”
Next blank white screen in in the then card “Turn Power On” by select the Zone. 
Next one is in the Then card “Power off/standby by select Zone. 
BTW This blank white screen is in all Then card wich Zone contains

**Comment by jwhomer** [comment]
Same, when selecten the ‘input’ card, and try to select which input the flow should change after power on, i get the white screen. All final versions 2.0, IOS.

**Comment by hilvarenbeek** [comment]
Should be fixed in 1.0.3

**Comment by hilvarenbeek** [comment]
Version 1.0.3 with fixes is now in beta on the app store. Please try this version. If I haven't introduced any new bugs, I will promote 1.0.3 to stable but would like it if a few people tested it first.

**Comment by jwhomer** [comment]
Almost there, can select input, but cant finish card. Its missing a zone, selecting a zone does not work, it cant find any. In other functions zone selecting is working.

**Comment by hilvarenbeek** [comment]
Indeed not fully fixed, working on a better fix now.

**Comment by hilvarenbeek** [comment]
Should be fixed in 1.0.4, do you have the possibility to install/run it from the repository using the athom SDK? I will do some more testing myself then submit it to the app store as beta.

**Comment by hilvarenbeek** [comment]
1.0.4 is now in beta on the Athom app store

**Comment by jwhomer** [comment]
I have tested 1.04 beta and can indeed select a zone and select input. Tested the action, and it works for me. Nice!

**Comment by hilvarenbeek** [comment]
thanks for checking!
