### ISSUE TITLE
Spotify connect seems to be broken

### ISSUE THREAD

**Issue by PeterKawa** [hilvarenbeek/nl.marcovandenhout.marantz#36]
(I've contacted Athom first about the Spotify app, but they point to the Marantz app.)
Marantz app v1.1.0
Homey v7.3.0

Dear Marco, I hope you are doing well.

The action cards like "playlist playback", "shuffle", "next", "play" all display the error "Device not found".  I re-paired the link to Spotify cloud, I can see and select the playlists like usual.

 The Marantz receiver simply responds to all commands from Homey.

 Via the Spotify mobile (cellphone) app I can play well on the Marantz.
 I've reinstalled both apps, restarted them, restarted Homey no avail.

 The step Removing and reinstalling apps I have not done for many flows which are then repaired have to be.
 It worked fine 1.5 years.

Diagn. Report: 0959fa3e-f674-473b-b3a0-ea2476e743e2

All the best,
Peter D.

**Comment by PeterKawa** [comment]
A Backup restore probably caused it. Re-creating devices and fixing flows was the reward 😏

**Comment by hilvarenbeek** [comment]
Thanks for the notice, unfortunately I'm not working on Homey anymore (I don't even have a working device to test it on).

**Comment by PeterKawa** [comment]
Ah I see. Are you willing to transfer the app to an other dev? (If found 🙃 ). 
If so,  I'll will mark it as such, and would you like to announce it in the readme.md?
Thanks for all your work, I enjoy using your app very much. 
All the best.

**Comment by hilvarenbeek** [comment]
Yes, I have no problem with another developer taking over the app. I'm not sure how to do that in Homey's App Store nor on GitHub (other than by simply forking it), but I'd be happy to 'sign it over' for Athom's purposes.
