### ISSUE TITLE
Zone select

### ISSUE THREAD

**Issue by itsamaik** [hilvarenbeek/nl.marcovandenhout.marantz#7]
Currently both zones on my SR5008B switch on, it would be nice to be able to select the zone or limit the action to the main zone.

**Comment by hilvarenbeek** [comment]
This should be fixed in version 0.0.3

**Comment by hilvarenbeek** [comment]
Can you try the 0.0.4 version in the Athom App Store? That should fix this issue.

**Comment by ghost** [comment]
I'll try it on sundayevening and let you know

**Comment by itsamaik** [comment]
Works like a charm!
